# -*- coding: utf-8 -*-
"""Hackathon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H_uobnSQ9gW-ncjMGWPIGvt4tGOv60E0
"""

!pip install spacy
!python -m spacy download en_core_web_md

import spacy

# Load model
nlp = spacy.load("en_core_web_md")

#ask claude to make a combined integrated code using this embeddings

import pandas as pd
import numpy as np
import warnings
import zipfile
import os
import glob
warnings.filterwarnings('ignore')

from sklearn.ensemble import RandomForestClassifier
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.model_selection import cross_val_score


# =============================================================================
# 0. FIND & EXTRACT ZIP FILE
# =============================================================================

def find_and_extract_zip(extract_dir='survey_data'):
    """
    Looks for a .zip file in the current directory (or any subdirectory one
    level deep). Extracts it into `extract_dir` and returns that path.
    If CSVs are already present in the current directory, returns '.'.
    """
    # Already extracted?
    if os.path.exists('survey_1_numbers.csv'):
        print("CSVs found in current directory.")
        return '.'

    # Search for a zip file
    zip_files = glob.glob('*.zip') + glob.glob('**/*.zip', recursive=False)
    if not zip_files:
        raise FileNotFoundError(
            "No .zip file found in the current directory. "
            "Please place the zip file (drive-download-*.zip) in the same "
            "folder as this script and re-run."
        )

    zip_path = zip_files[0]
    print(f"Found zip: {zip_path}  →  extracting to ./{extract_dir}/")
    os.makedirs(extract_dir, exist_ok=True)
    with zipfile.ZipFile(zip_path, 'r') as zf:
        zf.extractall(extract_dir)

    # Confirm the expected files are present
    expected = [
        'survey_1_numbers.csv', 'survey_2_numbers.csv',
        'survey_3_numbers.csv', 'survey_4_numbers.csv',
    ]
    missing = [f for f in expected if not os.path.exists(os.path.join(extract_dir, f))]
    if missing:
        raise FileNotFoundError(
            f"Extraction succeeded but these files were not found inside the zip: {missing}"
        )

    print(f"Extraction complete. Files in ./{extract_dir}/")
    return extract_dir


DATA_DIR = find_and_extract_zip()


# =============================================================================
# 1. DATA LOADING
# =============================================================================

def load_survey(filename):
    """
    Load a Qualtrics CSV export.
    Rows 0 and 1 are metadata (ImportId row + blank row); real data starts row 2.
    """
    path = os.path.join(DATA_DIR, filename)
    df = pd.read_csv(path, header=0, skiprows=[1, 2])
    return df


# Load all four surveys (numbers edition = numeric coded responses)
s1 = load_survey('survey_1_numbers.csv')
s2 = load_survey('survey_2_numbers.csv')
s3 = load_survey('survey_3_numbers.csv')
s4 = load_survey('survey_4_numbers.csv')

print(f"Survey 1: {s1.shape}  Survey 2: {s2.shape}")
print(f"Survey 3: {s3.shape}  Survey 4: {s4.shape}")


# =============================================================================
# 2. FEATURE ENGINEERING: SUBSCALE SCORES
# =============================================================================

def subscale_mean(df, prefix):
    """
    Average all columns whose name starts with `prefix` into a single score.
    Converts to numeric, coercing non-numeric to NaN before averaging.
    Returns a Series aligned to df's index.
    """
    cols = [c for c in df.columns if c.startswith(prefix)]
    if not cols:
        return None
    numeric = pd.to_numeric(
        df[cols].stack(future_stack=True), errors='coerce'
    ).unstack()
    return numeric.mean(axis=1)


#  Survey 2 constructs
s2_features = {
    'Individualism':        subscale_mean(s2, 'Individualism'),          # 16 items
    'Conscientiousness':    subscale_mean(s2, 'Conscientiousness'),       # 8 items
    'Beck_Anxiety':         subscale_mean(s2, 'Beck Anxiety '),           # 21 items
    'Social_Desirability':  subscale_mean(s2, 'Social Desirability'),     # 13 items
    'Risk_Aversion_1':      subscale_mean(s2, 'Risk Aversion 1 '),        # 14 items (elicitation 1)
    'Risk_Aversion_2':      subscale_mean(s2, 'Risk Aversion 2 '),        # 14 items (elicitation 2)
    'Risk_Aversion_3':      subscale_mean(s2, 'Risk Aversion 3 '),        # 14 items (elicitation 3)
    'Loss_Aversion_1':      subscale_mean(s2, 'Loss Aversion 1 '),        # 14 items
    'Loss_Aversion_2':      subscale_mean(s2, 'Loss Aversion 2 '),
    'Loss_Aversion_3':      subscale_mean(s2, 'Loss Aversion 3 '),
    'Discount_Rate_1':      subscale_mean(s2, 'Discount Rate 1 '),        # 9 items
    'Discount_Rate_2':      subscale_mean(s2, 'Discount rate 2 '),
    'Present_Bias_1':       subscale_mean(s2, 'Present bias 1 '),         # 9 items
    'Present_Bias_2':       subscale_mean(s2, 'Present bias 2 '),
    'Present_Bias_3':       subscale_mean(s2, 'Present bias 3 '),
}

#  Survey 3 constructs
s3_features = {
    'Need_Closure':         subscale_mean(s3, 'Need for closure'),        # 15 items
    'Need_Uniqueness':      subscale_mean(s3, 'Need for uniqueness'),     # 12 items
    'Self_Monitoring':      subscale_mean(s3, 'Self-Monitoring'),         # 13 items
    'Self_Clarity':         subscale_mean(s3, 'Self-Conc. Clarity'),      # 12 items
    'Regulatory_Focus':     subscale_mean(s3, 'Regulatory Focus'),        # 10 items
    'Maximization':         subscale_mean(s3, 'Maximization'),            # 6 items
}

# Combine into feature matrix; align on row index (respondent order is identical)
all_features = {**s2_features, **s3_features}
X = pd.DataFrame(all_features)

# Drop rows with any NaN (in practice: 0 rows dropped after subscale averaging)
X = X.dropna()

print(f"\nFeature matrix shape: {X.shape}")   # Expected: (233, 21)
print(f"Missing values: {X.isnull().sum().sum()}")


# 3. PCA EMBEDDINGS


scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Fit PCA; retain 8 components (~73% variance)
pca = PCA(n_components=8, random_state=42)
X_pca = pca.fit_transform(X_scaled)

var_exp = pca.explained_variance_ratio_
print("\nPCA explained variance per component:")
for i, v in enumerate(var_exp):
    print(f"  PC{i+1}: {v:.1%}  (cumulative: {var_exp[:i+1].sum():.1%})")

# Embedding DataFrame (one row per respondent)
embedding_df = pd.DataFrame(
    X_pca,
    columns=[f'embedding_pc{i+1}' for i in range(8)],
    index=X.index
)


# 4. K-MEANS CLUSTERING


kmeans = KMeans(n_clusters=4, random_state=42, n_init=10)
cluster_labels = kmeans.fit_predict(X_scaled)

print(f"\nK-Means (k=4) cluster sizes: {np.bincount(cluster_labels).tolist()}")

# Cluster profile: mean of key features per cluster
X_profiled = X.copy()
X_profiled['cluster'] = cluster_labels
profile_cols = [
    'Individualism', 'Conscientiousness', 'Beck_Anxiety',
    'Risk_Aversion_1', 'Loss_Aversion_1', 'Discount_Rate_1', 'Present_Bias_1'
]
print("\nCluster profiles (feature means):")
print(X_profiled.groupby('cluster')[profile_cols].mean().round(3))


# 5. RANDOM FOREST: FEATURE IMPORTANCE + CLUSTER PREDICTION

rf = RandomForestClassifier(n_estimators=200, random_state=42, n_jobs=-1)
rf.fit(X_scaled, cluster_labels)

# 5-fold cross-validated accuracy
cv_scores = cross_val_score(rf, X_scaled, cluster_labels, cv=5, scoring='accuracy')
print(f"\nRandom Forest 5-fold CV accuracy: {cv_scores.mean():.3f} ± {cv_scores.std():.3f}")

# Feature importances (sorted descending)
importances = pd.Series(rf.feature_importances_, index=X.columns).sort_values(ascending=False)
print("\nFeature importances (predicting cluster membership):")
for feat, imp in importances.items():
    bar = '█' * int(imp * 200)
    print(f"  {feat:<25} {imp:.4f}  {bar}")


# 6. ENRICH ORIGINAL CSVs WITH EMBEDDINGS + CLUSTER LABELS

def enrich_survey(original_path, output_path, embedding_df, cluster_labels, index):
    """
    Reload the original survey CSV, append PCA embeddings and cluster label,
    and save to a new file.
    """
    df_orig = pd.read_csv(original_path)  # keep all original rows including metadata

    # The actual respondent rows are offset by 2 (metadata rows 1 and 2)
    # We attach embeddings to the data rows only
    emb_cols = embedding_df.columns.tolist()
    for col in emb_cols + ['cluster']:
        df_orig[col] = np.nan  # initialise

    data_row_indices = range(2, 2 + len(index))   # rows 2..N in original file
    for i, (emb_row, clust) in enumerate(zip(embedding_df.values, cluster_labels)):
        for j, col in enumerate(emb_cols):
            df_orig.loc[2 + i, col] = round(float(emb_row[j]), 6)
        df_orig.loc[2 + i, 'cluster'] = int(clust)

    df_orig.to_csv(output_path, index=False)
    print(f"  Saved: {output_path}")


print("\nEnriching survey CSVs...")

# Survey 2 (primary enrichment — all constructs live here)
enrich_survey(
    original_path=os.path.join(DATA_DIR, 'survey_2_numbers.csv'),
    output_path=os.path.join(DATA_DIR, 'survey_2_numbers_enriched.csv'),
    embedding_df=embedding_df,
    cluster_labels=cluster_labels,
    index=X.index
)

# Survey 2 labels edition (same row alignment)
enrich_survey(
    original_path=os.path.join(DATA_DIR, 'survey_2_labels.csv'),
    output_path=os.path.join(DATA_DIR, 'survey_2_labels_enriched.csv'),
    embedding_df=embedding_df,
    cluster_labels=cluster_labels,
    index=X.index
)

# You can repeat for surveys 1, 3, 4 if respondents share the same row order:
# enrich_survey(os.path.join(DATA_DIR,'survey_1_numbers.csv'), os.path.join(DATA_DIR,'survey_1_numbers_enriched.csv'), ...)
# enrich_survey(os.path.join(DATA_DIR,'survey_3_numbers.csv'), os.path.join(DATA_DIR,'survey_3_numbers_enriched.csv'), ...)
# enrich_survey(os.path.join(DATA_DIR,'survey_4_numbers.csv'), os.path.join(DATA_DIR,'survey_4_numbers_enriched.csv'), ...)


# 7. QUICK SUMMARY STATISTICS


print("\n" + "="*60)
print("SUMMARY")
print("="*60)
print(f"Respondents:               {len(X)}")
print(f"Constructs (features):     {X.shape[1]}")
print(f"PCA components retained:   8  ({var_exp.sum():.1%} variance)")
print(f"Clusters (k-means):        4")
print(f"RF CV accuracy:            {cv_scores.mean():.1%}")
print(f"\nTop-3 most predictive features:")
for feat, imp in importances.head(3).items():
    print(f"  {feat}: {imp:.1%} importance")
print("\nKey finding: Economic preference measures (risk/loss aversion,")
print("present bias, discount rate) account for ~54% of RF signal,")
print("outweighing personality traits (anxiety, individualism, etc.)")

import pandas as pd
import numpy as np
import warnings
import zipfile
import os
import glob
import spacy

warnings.filterwarnings('ignore')

from sklearn.ensemble import RandomForestClassifier
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.model_selection import cross_val_score

# Load spaCy model (run: python -m spacy download en_core_web_md  if not installed)
nlp = spacy.load("en_core_web_md")


# =============================================================================
# 0. FIND & EXTRACT ZIP FILE
# =============================================================================

def find_and_extract_zip(extract_dir='survey_data'):
    """
    Looks for a .zip file in the current directory (or any subdirectory one
    level deep). Extracts it into `extract_dir` and returns that path.
    If CSVs are already present in the current directory, returns '.'.
    """
    # Already extracted?
    if os.path.exists('survey_1_numbers.csv'):
        print("CSVs found in current directory.")
        return '.'

    # Search for a zip file
    zip_files = glob.glob('*.zip') + glob.glob('**/*.zip', recursive=False)
    if not zip_files:
        raise FileNotFoundError(
            "No .zip file found in the current directory. "
            "Please place the zip file (drive-download-*.zip) in the same "
            "folder as this script and re-run."
        )

    zip_path = zip_files[0]
    print(f"Found zip: {zip_path}  →  extracting to ./{extract_dir}/")
    os.makedirs(extract_dir, exist_ok=True)
    with zipfile.ZipFile(zip_path, 'r') as zf:
        zf.extractall(extract_dir)

    # Confirm the expected files are present
    expected = [
        'survey_1_numbers.csv', 'survey_2_numbers.csv',
        'survey_3_numbers.csv', 'survey_4_numbers.csv',
    ]
    missing = [f for f in expected if not os.path.exists(os.path.join(extract_dir, f))]
    if missing:
        raise FileNotFoundError(
            f"Extraction succeeded but these files were not found inside the zip: {missing}"
        )

    print(f"Extraction complete. Files in ./{extract_dir}/")
    return extract_dir


DATA_DIR = find_and_extract_zip()


# =============================================================================
# 1. DATA LOADING
# =============================================================================

def load_survey(filename):
    """
    Load a Qualtrics CSV export.
    Rows 0 and 1 are metadata (ImportId row + blank row); real data starts row 2.
    """
    path = os.path.join(DATA_DIR, filename)
    df = pd.read_csv(path, header=0, skiprows=[1, 2])
    return df


# Load all four surveys (numbers edition = numeric coded responses)
s1 = load_survey('survey_1_numbers.csv')
s2 = load_survey('survey_2_numbers.csv')
s3 = load_survey('survey_3_numbers.csv')
s4 = load_survey('survey_4_numbers.csv')

print(f"Survey 1: {s1.shape}  Survey 2: {s2.shape}")
print(f"Survey 3: {s3.shape}  Survey 4: {s4.shape}")

# Print columns so you can identify open-text columns in surveys 1 and 4
print("\nSurvey 1 columns:", s1.columns.tolist())
print("\nSurvey 4 columns:", s4.columns.tolist())


# =============================================================================
# 2. FEATURE ENGINEERING: SUBSCALE SCORES
# =============================================================================

def subscale_mean(df, prefix):
    """
    Average all columns whose name starts with `prefix` into a single score.
    Converts to numeric, coercing non-numeric to NaN before averaging.
    Returns a Series aligned to df's index.
    """
    cols = [c for c in df.columns if c.startswith(prefix)]
    if not cols:
        return None
    numeric = pd.to_numeric(
        df[cols].stack(future_stack=True), errors='coerce'
    ).unstack()
    return numeric.mean(axis=1)


#  Survey 2 constructs
s2_features = {
    'Individualism':        subscale_mean(s2, 'Individualism'),          # 16 items
    'Conscientiousness':    subscale_mean(s2, 'Conscientiousness'),       # 8 items
    'Beck_Anxiety':         subscale_mean(s2, 'Beck Anxiety '),           # 21 items
    'Social_Desirability':  subscale_mean(s2, 'Social Desirability'),     # 13 items
    'Risk_Aversion_1':      subscale_mean(s2, 'Risk Aversion 1 '),        # 14 items (elicitation 1)
    'Risk_Aversion_2':      subscale_mean(s2, 'Risk Aversion 2 '),        # 14 items (elicitation 2)
    'Risk_Aversion_3':      subscale_mean(s2, 'Risk Aversion 3 '),        # 14 items (elicitation 3)
    'Loss_Aversion_1':      subscale_mean(s2, 'Loss Aversion 1 '),        # 14 items
    'Loss_Aversion_2':      subscale_mean(s2, 'Loss Aversion 2 '),
    'Loss_Aversion_3':      subscale_mean(s2, 'Loss Aversion 3 '),
    'Discount_Rate_1':      subscale_mean(s2, 'Discount Rate 1 '),        # 9 items
    'Discount_Rate_2':      subscale_mean(s2, 'Discount rate 2 '),
    'Present_Bias_1':       subscale_mean(s2, 'Present bias 1 '),         # 9 items
    'Present_Bias_2':       subscale_mean(s2, 'Present bias 2 '),
    'Present_Bias_3':       subscale_mean(s2, 'Present bias 3 '),
}

#  Survey 3 constructs
s3_features = {
    'Need_Closure':         subscale_mean(s3, 'Need for closure'),        # 15 items
    'Need_Uniqueness':      subscale_mean(s3, 'Need for uniqueness'),     # 12 items
    'Self_Monitoring':      subscale_mean(s3, 'Self-Monitoring'),         # 13 items
    'Self_Clarity':         subscale_mean(s3, 'Self-Conc. Clarity'),      # 12 items
    'Regulatory_Focus':     subscale_mean(s3, 'Regulatory Focus'),        # 10 items
    'Maximization':         subscale_mean(s3, 'Maximization'),            # 6 items
}


# =============================================================================
# 2b. TEXT EMBEDDINGS (spaCy) — surveys 1 & 4
# =============================================================================

def get_text_embedding(df, text_col):
    """
    For a given text column in a survey dataframe, compute a spaCy
    document-level embedding (mean of word vectors) for each respondent.
    Returns a DataFrame with 300 columns: text_embed_0 ... text_embed_299.
    Rows with missing/empty text get a zero vector.
    """
    texts = df[text_col].fillna("").astype(str).tolist()

    vectors = []
    for doc in nlp.pipe(texts, batch_size=50):   # nlp.pipe is faster than a plain loop
        vectors.append(doc.vector)               # 300-dim averaged word vector

    embed_df = pd.DataFrame(
        vectors,
        columns=[f'text_embed_{i}' for i in range(300)],
        index=df.index
    )
    return embed_df


def compress_text_embeds(embed_df, n_components=5, prefix='txt'):
    """
    Reduce 300-dim text embeddings to n_components via PCA.
    This prevents the 300 raw dimensions from drowning out the
    21 subscale features in the main feature matrix.
    """
    pca_text = PCA(n_components=n_components, random_state=42)
    compressed = pca_text.fit_transform(
        StandardScaler().fit_transform(embed_df)
    )
    return pd.DataFrame(
        compressed,
        columns=[f'{prefix}_pc{i+1}' for i in range(n_components)],
        index=embed_df.index
    )


# ------------------------------------------------------------------
# *** ACTION REQUIRED ***
# Replace the strings below with the actual open-text column names
# from your surveys. Run the script once first to see column names
# printed above, then update these values and re-run.
# If a survey has NO open-text columns, set its variable to None.
# ------------------------------------------------------------------
S1_TEXT_COL = 'open_response'    # <-- replace with real column name from survey 1
S4_TEXT_COL = 'open_response'    # <-- replace with real column name from survey 4

# Build text embedding features (only if the column exists in the dataframe)
text_features = {}

if S1_TEXT_COL and S1_TEXT_COL in s1.columns:
    print(f"\nComputing spaCy embeddings for Survey 1 → '{S1_TEXT_COL}' ...")
    s1_raw_embeds  = get_text_embedding(s1, S1_TEXT_COL)          # (n, 300)
    s1_txt_pca     = compress_text_embeds(s1_raw_embeds, n_components=5, prefix='s1_txt')
    text_features.update(s1_txt_pca.to_dict(orient='series'))
    print(f"  Survey 1 text embeddings compressed to {s1_txt_pca.shape[1]} PCA dims.")
else:
    print(f"\n[Skip] Survey 1 text column '{S1_TEXT_COL}' not found — skipping text embeddings.")

if S4_TEXT_COL and S4_TEXT_COL in s4.columns:
    print(f"Computing spaCy embeddings for Survey 4 → '{S4_TEXT_COL}' ...")
    s4_raw_embeds  = get_text_embedding(s4, S4_TEXT_COL)          # (n, 300)
    s4_txt_pca     = compress_text_embeds(s4_raw_embeds, n_components=5, prefix='s4_txt')
    text_features.update(s4_txt_pca.to_dict(orient='series'))
    print(f"  Survey 4 text embeddings compressed to {s4_txt_pca.shape[1]} PCA dims.")
else:
    print(f"[Skip] Survey 4 text column '{S4_TEXT_COL}' not found — skipping text embeddings.")


# =============================================================================
# 2c. COMBINE ALL FEATURES
# =============================================================================

all_features = {**s2_features, **s3_features, **text_features}
X = pd.DataFrame(all_features)

# Drop rows with any NaN
X = X.dropna()

print(f"\nFeature matrix shape: {X.shape}")
print(f"  → {len(s2_features)} subscale features (Survey 2)")
print(f"  → {len(s3_features)} subscale features (Survey 3)")
print(f"  → {len(text_features)} compressed text embedding dims (Surveys 1 & 4)")
print(f"Missing values: {X.isnull().sum().sum()}")


# =============================================================================
# 3. PCA EMBEDDINGS
# =============================================================================

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Fit PCA; retain 8 components (~73% variance for original 21-feature set;
# may capture slightly more variance now that text features are included)
pca = PCA(n_components=8, random_state=42)
X_pca = pca.fit_transform(X_scaled)

var_exp = pca.explained_variance_ratio_
print("\nPCA explained variance per component:")
for i, v in enumerate(var_exp):
    print(f"  PC{i+1}: {v:.1%}  (cumulative: {var_exp[:i+1].sum():.1%})")

# Embedding DataFrame (one row per respondent)
embedding_df = pd.DataFrame(
    X_pca,
    columns=[f'embedding_pc{i+1}' for i in range(8)],
    index=X.index
)


# =============================================================================
# 4. K-MEANS CLUSTERING
# =============================================================================

kmeans = KMeans(n_clusters=4, random_state=42, n_init=10)
cluster_labels = kmeans.fit_predict(X_scaled)

print(f"\nK-Means (k=4) cluster sizes: {np.bincount(cluster_labels).tolist()}")

# Cluster profile: mean of key features per cluster
X_profiled = X.copy()
X_profiled['cluster'] = cluster_labels
profile_cols = [
    'Individualism', 'Conscientiousness', 'Beck_Anxiety',
    'Risk_Aversion_1', 'Loss_Aversion_1', 'Discount_Rate_1', 'Present_Bias_1'
]
print("\nCluster profiles (feature means):")
print(X_profiled.groupby('cluster')[profile_cols].mean().round(3))


# =============================================================================
# 5. RANDOM FOREST: FEATURE IMPORTANCE + CLUSTER PREDICTION
# =============================================================================

rf = RandomForestClassifier(n_estimators=200, random_state=42, n_jobs=-1)
rf.fit(X_scaled, cluster_labels)

# 5-fold cross-validated accuracy
cv_scores = cross_val_score(rf, X_scaled, cluster_labels, cv=5, scoring='accuracy')
print(f"\nRandom Forest 5-fold CV accuracy: {cv_scores.mean():.3f} ± {cv_scores.std():.3f}")

# Feature importances (sorted descending)
importances = pd.Series(rf.feature_importances_, index=X.columns).sort_values(ascending=False)
print("\nFeature importances (predicting cluster membership):")
for feat, imp in importances.items():
    bar = '█' * int(imp * 200)
    print(f"  {feat:<25} {imp:.4f}  {bar}")


# =============================================================================
# 6. ENRICH ORIGINAL CSVs WITH EMBEDDINGS + CLUSTER LABELS
# =============================================================================

def enrich_survey(original_path, output_path, embedding_df, cluster_labels, index):
    """
    Reload the original survey CSV, append PCA embeddings and cluster label,
    and save to a new file.
    """
    df_orig = pd.read_csv(original_path)  # keep all original rows including metadata

    # The actual respondent rows are offset by 2 (metadata rows 1 and 2)
    # We attach embeddings to the data rows only
    emb_cols = embedding_df.columns.tolist()
    for col in emb_cols + ['cluster']:
        df_orig[col] = np.nan  # initialise

    for i, (emb_row, clust) in enumerate(zip(embedding_df.values, cluster_labels)):
        for j, col in enumerate(emb_cols):
            df_orig.loc[2 + i, col] = round(float(emb_row[j]), 6)
        df_orig.loc[2 + i, 'cluster'] = int(clust)

    df_orig.to_csv(output_path, index=False)
    print(f"  Saved: {output_path}")


print("\nEnriching survey CSVs...")

# Survey 2 numbers
enrich_survey(
    original_path=os.path.join(DATA_DIR, 'survey_2_numbers.csv'),
    output_path=os.path.join(DATA_DIR, 'survey_2_numbers_enriched.csv'),
    embedding_df=embedding_df,
    cluster_labels=cluster_labels,
    index=X.index
)

# Survey 2 labels edition (same row alignment)
enrich_survey(
    original_path=os.path.join(DATA_DIR, 'survey_2_labels.csv'),
    output_path=os.path.join(DATA_DIR, 'survey_2_labels_enriched.csv'),
    embedding_df=embedding_df,
    cluster_labels=cluster_labels,
    index=X.index
)

# Survey 1, 3, 4 — uncomment once you've confirmed row alignment matches
# enrich_survey(
#     original_path=os.path.join(DATA_DIR, 'survey_1_numbers.csv'),
#     output_path=os.path.join(DATA_DIR, 'survey_1_numbers_enriched.csv'),
#     embedding_df=embedding_df, cluster_labels=cluster_labels, index=X.index
# )
# enrich_survey(
#     original_path=os.path.join(DATA_DIR, 'survey_3_numbers.csv'),
#     output_path=os.path.join(DATA_DIR, 'survey_3_numbers_enriched.csv'),
#     embedding_df=embedding_df, cluster_labels=cluster_labels, index=X.index
# )
# enrich_survey(
#     original_path=os.path.join(DATA_DIR, 'survey_4_numbers.csv'),
#     output_path=os.path.join(DATA_DIR, 'survey_4_numbers_enriched.csv'),
#     embedding_df=embedding_df, cluster_labels=cluster_labels, index=X.index
# )


# =============================================================================
# 7. QUICK SUMMARY STATISTICS
# =============================================================================

print("\n" + "="*60)
print("SUMMARY")
print("="*60)
print(f"Respondents:               {len(X)}")
print(f"Constructs (features):     {X.shape[1]}")
print(f"  Subscale features:       {len(s2_features) + len(s3_features)}")
print(f"  Text embedding dims:     {len(text_features)}")
print(f"PCA components retained:   8  ({var_exp.sum():.1%} variance)")
print(f"Clusters (k-means):        4")
print(f"RF CV accuracy:            {cv_scores.mean():.1%}")
print(f"\nTop-3 most predictive features:")
for feat, imp in importances.head(3).items():
    print(f"  {feat}: {imp:.1%} importance")
print("\nKey finding: Economic preference measures (risk/loss aversion,")
print("present bias, discount rate) account for ~54% of RF signal,")
print("outweighing personality traits (anxiety, individualism, etc.)")

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, Normalizer
from sklearn.decomposition import TruncatedSVD
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.impute import SimpleImputer

def generate_survey_embeddings(labels_files, numbers_files, output_dim=64):
    """
    Integrates 8 survey files into a unified latent embedding space.
    """
    all_num_dfs = []
    all_lab_dfs = []

    print("Cleaning and loading files...")
    for nf, lf in zip(numbers_files, labels_files):
        # 1. Load and Skip Metadata Rows (Row 0: Text, Row 1: Qualtrics IDs)
        df_num = pd.read_csv(nf).iloc[2:]
        df_lab = pd.read_csv(lf).iloc[2:]

        # 2. Clean and Index by person_id
        for df in [df_num, df_lab]:
            df.dropna(subset=['person_id'], inplace=True)
            df['person_id'] = df['person_id'].astype(str).str.strip()
            df.set_index('person_id', inplace=True)

        # 3. Numeric Path Cleaning: Force numbers and handle 'inf'
        df_num = df_num.apply(pd.to_numeric, errors='coerce')
        df_num = df_num.replace([np.inf, -np.inf], np.nan)

        # 4. Feature Selection: Drop columns with >95% missing values
        df_num = df_num.dropna(axis=1, thresh=int(0.05 * len(df_num)))

        # Prefix columns to avoid collisions between surveys
        survey_id = nf.split('_')[1]
        df_num.columns = [f"s{survey_id}_{c}" for c in df_num.columns]
        df_lab.columns = [f"s{survey_id}_{c}" for c in df_lab.columns]

        all_num_dfs.append(df_num)
        all_lab_dfs.append(df_lab)

    # 5. Harmonize: Merge all surveys into Master Matrices
    df_num_master = pd.concat(all_num_dfs, axis=1).dropna(how='all')
    df_lab_master = pd.concat(all_lab_dfs, axis=1).reindex(df_num_master.index)

    print(f"Generating embeddings for {len(df_num_master)} respondents...")

    # PATH A: Numerical Latent Representation
    imputer = SimpleImputer(strategy='median')
    X_num = imputer.fit_transform(df_num_master)
    scaler = MinMaxScaler()
    X_num_scaled = scaler.fit_transform(X_num)

    svd_num = TruncatedSVD(n_components=output_dim, random_state=42)
    emb_num = svd_num.fit_transform(X_num_scaled)

    # PATH B: Semantic Label Representation
    text_data = df_lab_master.fillna('').astype(str).apply(lambda row: ' '.join(row), axis=1)
    vectorizer = TfidfVectorizer(max_features=1000, stop_words='english')
    X_text = vectorizer.fit_transform(text_data)

    svd_text = TruncatedSVD(n_components=output_dim, random_state=42)
    emb_text = svd_text.fit_transform(X_text)

    # FUSION: Concatenate and Normalize
    fusion = np.hstack((emb_num, emb_text))
    normalizer = Normalizer()
    final_embeddings = normalizer.fit_transform(fusion)

    # Convert to DataFrame
    cols = [f'embedding_dim_{i}' for i in range(final_embeddings.shape[1])]
    result_df = pd.DataFrame(final_embeddings, columns=cols, index=df_num_master.index)

    return result_df

# List your files in pairs
labels = ['survey_1_labels.csv', 'survey_2_labels.csv', 'survey_3_labels.csv', 'survey_4_labels.csv']
numbers = ['survey_1_numbers.csv', 'survey_2_numbers.csv', 'survey_3_numbers.csv', 'survey_4_numbers.csv']

# Generate and save
embeddings = generate_survey_embeddings(labels, numbers)
embeddings.to_csv('final_survey_embeddings.csv')
print("Successfully saved embeddings to 'final_survey_embeddings.csv'")